check dependencies [future: delete from formulae]

diff --git a/bin/nef b/bin/nef
--- a/bin/nef
+++ b/bin/nef
@@ -55,6 +55,7 @@ printHelpPlayground() {
     echo "    Build a playground compatible with external frameworks"
     echo ""
     echo "    ${optional}${bold}--name${reset}${normal} specify the name for the Xcode project that you are creating ${optional}[default: $DEFAULT_PLAYGROUND]${reset}"
+    echo ""
     echo "    ${optional}${bold}--bow-version${reset}${normal} specify the version of Bow that you want to use in the project ${optional}[optional]${reset}"
     echo "    ${optional}${bold}--bow-branch${reset}${normal} specify the branch of Bow that you want to use in the project ${optional}[optional]${reset}"
     echo "    ${optional}${bold}--podfile${reset}${normal} specify a Podfile with your own dependencies ${optional}[optional]${reset}"
@@ -78,6 +79,38 @@ printHelpCompileClean() {
     echo ""
     echo "    ${required}${bold}<path>${reset}${normal} path to the folder where the project and playgrounds are located"
     echo ""
+}
+
+#: - Dependencies
+
+##
+# checkDependencies() throws
+##
+checkDependencies() {
+  checkCocoaPods
+}
+
+##
+#   checkCocoaPods() throws
+##
+checkCocoaPods() {
+  totalCommandsPod=$(command -v pod | wc -l)
+  if [ $totalCommandsPod -eq 0 ]; then
+    echo "[!] ${bold}${red}error: ${reset}required cocoapods. Please ${bold}install cocoapods${reset}. Run: 'sudo gem install cocoapods'"
+    exit 1
+  fi
+
+  requiredVersion='1.6.1'
+  podVersion=`pod --version`
+  minorPodVersionRequired=(`printf "$podVersion\n$requiredVersion\n" | sort`)
+
+  if [ "$minorPodVersionRequired" != "$requiredVersion" ]; then
+    echo "[!] ${bold}${red}error: ${reset}required cocoapods version ${bold}'$requiredVersion'${normal} [found: ${red}'$podVersion'${reset}]"
+    echo ""
+    echo "Please ${bold}update your cocoapods${reset}. Run: 'sudo gem install cocoapods'"
+    echo ""
+    exit 1
+  fi
 }
 
 #: - Jekyll
@@ -231,6 +264,8 @@ clean() {
 
 #: - MAIN
 set -e
+
+checkDependencies
 
 while [ "$1" != "" ]; do
     case $1 in
