added clean option

diff --git a/bin/nef b/bin/nef
--- a/bin/nef
+++ b/bin/nef
@@ -3,6 +3,7 @@
 #: Valid Args
 PLAYGROUND="playground"
 COMPILE="compile"
+CLEAN="clean"
 
 #: Default params
 DEFAULT_PLAYGROUND="BowPlayground"
@@ -22,13 +23,40 @@ reset=$(tput sgr0)
 #   printHelp()
 ##
 printHelp() {
+    printHelpPlayground $@
+    printHelpCompileClean $@
+}
+
+##
+#   printHelpPlayground()
+##
+printHelpPlayground() {
     echo ""
-    echo "${normal}$0 ${bold}$PLAYGROUND${normal} | ${bold}$COMPILE${normal} [${bold}--name${normal} <project>] [${bold}--version${normal} <number format: 0.0.0>]"
+    echo "${normal}$0 ${bold}$PLAYGROUND${normal} [${bold}--name${normal} <project>] [${bold}--version${normal} <number format: 0.0.0>]"
     echo ""
     echo "    ${green}${bold}$PLAYGROUND${reset}${normal} build a playground with Bow compatibility."
-    echo "    ${green}${bold}$COMPILE${reset}${normal} compile a Bow's playground."
     echo "    ${lime}${bold}name${reset}${normal} create a playground project using this name [optional]."
     echo "    ${lime}${bold}version${reset}${normal} bow's version to use [optional]."
+    echo ""
+}
+
+##
+#   printHelpCompileClean()
+##
+printHelpCompile() {
+    printHelpCompileClean
+}
+
+printHelpClean() {
+    printHelpCompileClean
+}
+
+printHelpCompileClean() {
+    echo ""
+    echo "${normal}$0 ${bold}$COMPILE${normal} | ${bold}$CLEAN${normal} <project>"
+    echo ""
+    echo "    ${green}${bold}$COMPILE${reset}${normal} compile a Bow's playground."
+    echo "    ${green}${bold}$CLEAN${reset}${normal} clean nef dependencies in Bow's playground."
     echo ""
 }
 
@@ -47,7 +75,9 @@ playground() {
             -n | --name )    shift; projectName=$1 ;;
             -v | --version ) shift; version=$1 ;;
             $PLAYGROUND )    ;;
-            * )              printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
+            $COMPILE )       printHelpPlayground; exit 1 ;;
+            $CLEAN )         printHelpPlayground; exit 1 ;;
+            * )              printHelpPlayground $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
         esac
         shift
     done
@@ -72,9 +102,12 @@ compile() {
 
     while [ "$1" != "" ]; do
         case $1 in
-            -n | --name )    shift; projectFolder=$1 ;;
-            $COMPILE )       ;;
-            * )              printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
+            $COMPILE )       shift; projectFolder=$1 ;;
+            -n | --name )    printHelpCompile; exit 1 ;;
+            -v | --version ) printHelpCompile; exit 1 ;;
+            $PLAYGROUND )    printHelpCompile; exit 1 ;;
+            $CLEAN )         printHelpCompile; exit 1 ;;
+            * )              printHelpCompile; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
         esac
         shift
     done
@@ -82,7 +115,35 @@ compile() {
     if [ "${#projectFolder}" -gt 0 ]; then
       nefc compile "$projectFolder"
     else
-      printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} command format."; exit 1
+      printHelpCompile; echo "${bold}[!] ${normal}${red}error:${reset} command format."; exit 1
+    fi
+}
+
+#: - Clean
+
+##
+#   clean(List<String> args)
+#   - Parameter `args`: list of command line arguments
+##
+clean() {
+    projectFolder=""
+
+    while [ "$1" != "" ]; do
+        case $1 in
+            $CLEAN )         shift; projectFolder=$1 ;;
+            -n | --name )    printHelpClean; exit 1 ;;
+            -v | --version ) printHelpClean; exit 1 ;;
+            $PLAYGROUND )    printHelpClean; exit 1 ;;
+            $COMPILE )       printHelpClean; exit 1 ;;
+            * )              printHelpClean; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
+        esac
+        shift
+    done
+
+    if [ "${#projectFolder}" -gt 0 ]; then
+      nefc clean "$projectFolder"
+    else
+      printHelpClean; echo "${bold}[!] ${normal}${red}error:${reset} command format."; exit 1
     fi
 }
 
@@ -91,12 +152,13 @@ set -e
 
 while [ "$1" != "" ]; do
     case $1 in
-        $PLAYGROUND ) shift; playground $@; exit 0 ;;
-        $COMPILE )    shift; compile $@; exit 0 ;;
-        -h | --help | help )  printHelp $@; exit 0 ;;
-        * )                   printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1
+        $PLAYGROUND ) playground $@; exit 0 ;;
+        $COMPILE )    compile $@; exit 0 ;;
+        $CLEAN )      clean $@; exit 0 ;;
+        -h | --help | help )  printHelp; exit 0 ;;
+        * )                   printHelp; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1
     esac
     shift
 done
 
-printHelp $@; exit 1
+printHelp; exit 1
