update `nef` to support nef-jekyll

diff --git a/bin/nef b/bin/nef
--- a/bin/nef
+++ b/bin/nef
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 #: Valid Args
+JEKYLL="jekyll"
 PLAYGROUND="playground"
 COMPILE="compile"
 CLEAN="clean"
@@ -23,8 +24,22 @@ reset=$(tput sgr0)
 #   printHelp()
 ##
 printHelp() {
+    printHelpJekyll $@
     printHelpPlayground $@
     printHelpCompileClean $@
+}
+
+##
+#   printHelpJekyll()
+##
+printHelpJekyll() {
+    echo ""
+    echo "${normal}$0 ${bold}$JEKYLL${normal} ${normal}<project> ${bold}--output${normal} <output> [${bold}--main-page${normal} <main-page>]${reset}"
+    echo ""
+    echo "    ${green}${bold}$JEKYLL${reset}${normal} render documentation compatible with Jekyll from source playgrounds"
+    echo "    ${lime}${bold}--output${reset}${normal} path where to render the Jekyll site"
+    echo "    ${lime}${bold}--main-page${reset}${normal} the main page in Jekyll file format [optional]${reset}"
+    echo ""
 }
 
 ##
@@ -34,9 +49,9 @@ printHelpPlayground() {
     echo ""
     echo "${normal}$0 ${bold}$PLAYGROUND${normal} [${bold}--name${normal} <project>] [${bold}--version${normal} <number format: 0.0.0>]"
     echo ""
-    echo "    ${green}${bold}$PLAYGROUND${reset}${normal} build a playground with Bow compatibility."
-    echo "    ${lime}${bold}name${reset}${normal} create a playground project using this name [optional]."
-    echo "    ${lime}${bold}version${reset}${normal} bow's version to use [optional]."
+    echo "    ${green}${bold}$PLAYGROUND${reset}${normal} build a playground with Bow compatibility"
+    echo "    ${lime}${bold}--name${reset}${normal} create a playground project using this name [optional]"
+    echo "    ${lime}${bold}--version${reset}${normal} bow's version to use [optional]"
     echo ""
 }
 
@@ -63,6 +78,37 @@ printHelpCompileClean() {
 #: - Playground
 
 ##
+#   jekyll(List<String> args)
+#   - Parameter `args`: list of command line arguments
+##
+jekyll() {
+  projectPath=""
+  outputPath=""
+  mainPagePath=""
+
+  while [ "$1" != "" ]; do
+      case $1 in
+          $JEKYLL )          shift; projectPath=$1 ;;
+          -o | --output )    shift; outputPath=$1 ;;
+          -m | --main-page ) shift; mainPagePath=$1 ;;
+          -n | --name )      printHelpJekyll; exit 1 ;;
+          -v | --version )   printHelpJekyll; exit 1 ;;
+          $PLAYGROUND )    printHelpJekyll; exit 1 ;;
+          $COMPILE )       printHelpJekyll; exit 1 ;;
+          $CLEAN )         printHelpJekyll; exit 1 ;;
+          * )              printHelpJekyll; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
+      esac
+      shift
+  done
+
+  if [ "$projectPath" == "" ] || [ "$outputPath" == "" ]; then
+      printHelpJekyll; exit 1
+  else
+      ~/Documents/3.projects/47deg/nef/bin/nef-jekyll --project "$projectPath" --output "$outputPath" --main-page "$mainPagePath"
+  fi
+}
+
+##
 #   playground(List<String> args)
 #   - Parameter `args`: list of command line arguments
 ##
@@ -72,9 +118,12 @@ playground() {
 
     while [ "$1" != "" ]; do
         case $1 in
+            $PLAYGROUND )    ;;
             -n | --name )    shift; projectName=$1 ;;
             -v | --version ) shift; version=$1 ;;
-            $PLAYGROUND )    ;;
+            -o | --output )    printHelpPlayground; exit 1 ;;
+            -m | --main-page ) printHelpPlayground; exit 1 ;;
+            $JEKYLL )        printHelpPlayground; exit 1 ;;
             $COMPILE )       printHelpPlayground; exit 1 ;;
             $CLEAN )         printHelpPlayground; exit 1 ;;
             * )              printHelpPlayground $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
@@ -102,9 +151,12 @@ compile() {
 
     while [ "$1" != "" ]; do
         case $1 in
-            $COMPILE )       shift; projectFolder=$1 ;;
-            -n | --name )    printHelpCompile; exit 1 ;;
-            -v | --version ) printHelpCompile; exit 1 ;;
+            $COMPILE )         shift; projectFolder=$1 ;;
+            -n | --name )      printHelpCompile; exit 1 ;;
+            -v | --version )   printHelpCompile; exit 1 ;;
+            -o | --output )    printHelpCompile; exit 1 ;;
+            -m | --main-page ) printHelpCompile; exit 1 ;;
+            $JEKYLL )        printHelpCompile; exit 1 ;;
             $PLAYGROUND )    printHelpCompile; exit 1 ;;
             $CLEAN )         printHelpCompile; exit 1 ;;
             * )              printHelpCompile; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
@@ -131,8 +183,11 @@ clean() {
     while [ "$1" != "" ]; do
         case $1 in
             $CLEAN )         shift; projectFolder=$1 ;;
-            -n | --name )    printHelpClean; exit 1 ;;
-            -v | --version ) printHelpClean; exit 1 ;;
+            -n | --name )      printHelpCompile; exit 1 ;;
+            -v | --version )   printHelpCompile; exit 1 ;;
+            -o | --output )    printHelpJekyll; exit 1 ;;
+            -m | --main-page ) printHelpJekyll; exit 1 ;;
+            $JEKYLL )        printHelpClean; exit 1 ;;
             $PLAYGROUND )    printHelpClean; exit 1 ;;
             $COMPILE )       printHelpClean; exit 1 ;;
             * )              printHelpClean; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}."; exit 1 ;;
@@ -152,6 +207,7 @@ set -e
 
 while [ "$1" != "" ]; do
     case $1 in
+        $JEKYLL )     jekyll $@; exit 0 ;;
         $PLAYGROUND ) playground $@; exit 0 ;;
         $COMPILE )    compile $@; exit 0 ;;
         $CLEAN )      clean $@; exit 0 ;;
