build jekyll files from playgrounds

diff --git a/bin/nef-doc b/bin/nef-doc
--- a/bin/nef-doc
+++ b/bin/nef-doc
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 LOG_PATH="/nef/docs"
+BASE_JEKYLL='docs'
 
 #: terminal setup
 bold=$(tput bold)
@@ -41,20 +42,39 @@ generateDocumentation() {
 
 buildMicrosite() {
     local projectPath="$1"
-    local sitePath="$2"
+    local sitePath="$2/$BASE_JEKYLL"
 
+    cleanStructure "$2"
+    mkdir -p "$sitePath"
     playgrounds "$projectPath"
-    for playground in "${playgrounds[@]}"; do
 
+    for playground in "${playgrounds[@]}"; do
         playgroundName=`echo "$playground" | rev | cut -d'/' -f -1 | cut -d'.' -f 2- | rev`
         playgroundPath="$projectPath/$playground"
 
+        echo -ne "${normal}Rendering jekyll file from ${green}Playground ($playgroundName)${reset}..."
         pagesInPlayground "$playgroundPath"
+
         for pagePath in "${pagesInPlayground[@]}"; do
             pageName=`echo "$pagePath" | rev | cut -d'/' -f -1 | cut -d'.' -f 2- | rev`
-            echo "page: $pagePath ($pageName :: $playgroundName)"
+            output="$sitePath/$playgroundName/$pageName"
+            permalink="/$BASE_JEKYLL/$playgroundName/$pageName/"
+
+            logFile="$LOG_PATH/$playgroundName-$pageName.log"
+            log="$projectPath/$logFile"
+
+            mkdir -p "$output"
+            nef-jekyll-page --from "$pagePath" --to "$output" --permalink "$permalink" 1> "$log" 2>&1
+
+            installed=`grep "RENDER SUCCEEDED" "$log"`
+            if [ "${#installed}" -lt 7 ]; then
+              echo " ❌"
+              echo "${bold}${red}error: ${reset}render page ${bold}$pageName${normal} in playground ${bold}$playgroundName${normal}, review '<project>$logFile' for more information."
+              exit 1
+            fi
         done
-        echo "-----------------------"
+
+        echo " ✅"
     done
 }
 
@@ -126,12 +146,12 @@ workspaceForProjectPath() {
 
     if [ "$numberOfWorkspaces" -ne 1 ]; then
         echo "[!] error: found more than 1 workspace (total:$numberOfWorkspaces): '$workspace'" > "$log"
-        exit -1
+        exit 1
     elif [ -d "$workspacePath" ]; then
         echo $workspacePath
     else
         echo "[!] error: not found any workspace in root project '$path'" > "$log"
-        exit -1
+        exit 1
     fi
 }
 
@@ -141,17 +161,17 @@ workspaceForProjectPath() {
 ##
 makeStructure() {
   set +e
-  local project="$1"  # parameter `project`
+  local logPath="$1/$LOG_PATH"  # parameter `project`
 
-  cleanStructure "$project"
-  mkdir -p "$project/$LOG_PATH"
+  cleanStructure "$logPath"
+  mkdir -p "$logPath"
 }
 
 cleanStructure() {
   set +e
-  local project="$1"  # parameter `folder`
+  local folder="$1"  # parameter `folder`
 
-  rm -rf "$project/$LOG_PATH" 1>/dev/null 2>/dev/null
+  rm -rf "$folder" 1>/dev/null 2>/dev/null
 }
 
 
