added structure for dependency manager to create playground

diff --git a/bin/nef-playground b/bin/nef-playground
--- a/bin/nef-playground
+++ b/bin/nef-playground
@@ -22,109 +22,150 @@ printHelp() {
     latestVersion=$(lastestBowVersion)
 
     echo ""
-    echo "${normal}nef-payground ${bold}--name ${normal}<project> ${bold}--bow-version ${normal}<number format: 0.0.0> ${bold}--bow-branch ${normal}<branch> ${bold}--podfile ${normal}<branch>"
+    echo "${normal}nef-payground ${bold}--name ${normal}<project> ${bold}--platform ${normal}<ios|osx> ${bold}--bow-version ${normal}<number format: 0.0.0> ${bold}--bow-branch ${normal}<branch> ${bold}--podfile ${normal}<path> ${bold}--cartfile ${normal}<path>"
     echo ""
     echo "    ${lime}${bold}--name${reset}${normal} create a playground project using this name [default: $DEFAULT_PLAYGROUND]"
+    echo "    ${lime}${bold}--platform${reset}${normal} create a iOS or macOS playground project [default: ios, values: ios | osx]"
     echo ""
     echo "    ${lime}${bold}--bow-version${reset}${normal} Bow's version to use [default: $latestVersion]"
     echo "    ${lime}${bold}--bow-branch${reset}${normal} Bow's branch to use [optional]"
     echo "    ${lime}${bold}--podfile${reset}${normal} podfile to use in playground [optional]"
+    echo "    ${lime}${bold}--cartfile${reset}${normal} cartfile to use in playground [optional]"
     echo "${reset}"
 }
 
 #: - Playground
 
 ##
-#   setDependency(String projectFolder, String projectName, String version, String branch, String podfile)
+#   setDependency(String projectFolder, String projectName, String platform, String version, String branch, String cartfile, String podfile) throws
 #   - Parameter `projectFolder`: path to the project folder.
 #   - Parameter `projectName`: the project name.
+#   - Parameter `platform`: set this platform to playground.
 #   - Parameter `version`: Bow's version which update Podfile.
 #   - Parameter `branch`: Bow's branch which update Podfile.
+#   - Parameter `cartfile`
 #   - Parameter `podfile`
 ##
 setDependency() {
   local projectFolder="$1" # parameter `projectFolder`
   local projectName="$2"   # parameter `projectName`
-  local version="$3"       # parameter `version`
-  local branch="$4"        # parameter `branch`
-  local podfile="$5"       # parameter `podfile`
-  local podfilePath="$projectFolder/Podfile"
+  local platform="$3"      # parameter `platform`
 
-  setPlaygroundPlatform "$projectFolder" "$projectName" "$podfile"
+  local version="$4"       # parameter `version`
+  local branch="$5"        # parameter `branch`
+  local cartfile="$6"      # parameter `cartfile`
+  local podfile="$7"       # parameter `podfile`
 
-  echo -ne "${normal}Updating ${green}"
-
-  if [ -f "$podfilePath" ]; then
-      # A. update Podfile using `branch`
-      if [ "$branch" != "" ]; then
-          echo -ne "branch ($branch)${reset}..."
-          branch=$(echo "$branch" | sed 's/\//\\\//g')
-          sed -i '' s/"\"~> 0.0.0\""/":git => 'https\:\/\/github.com\/bow-swift\/bow.git', :branch => '$branch'"/g "$podfilePath"
-          echo " ✅"
-
-      # B. update Podfile using 'podfile'
-      elif [ "$podfile" != "" ] & [ -f "$podfile" ]; then
-          podfileName=`echo "$podfile" | rev | cut -d'/' -f -1 | rev`
-          echo -ne "podfile ($podfileName)${reset}..."
-
-          rm -rf "$podfilePath" 1>/dev/null 2>/dev/null
-          cp "$podfile" "$podfilePath" 1>/dev/null 2>/dev/null
-
-          target=`cat "$podfilePath" | grep "target"`
-          sed -i '' s/"$target"/"target '$projectName' do"/g "$podfilePath"
-
-          echo " ✅"
-
-      # C. update Podfile using `version`
-      else
-          echo -ne "version ($version)${reset}..."
-          sed -i '' s/"~> 0.0.0"/"~> $version"/g "$podfilePath"
-          echo " ✅"
-      fi
-  else
-      echo " ❌"
-      echo "[!] ${bold}${red}error: ${reset}can not find file '$podfilePath'"
-      exit 1
+  if [ "$podfile" != "" ] & [ -f "$podfile" ]; then
+      setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "cocoapods"
+      setCocoaPodsDependency "$projectFolder" "$projectName" "$platform" "$podfile"
+  elif [ "$cartfile" != "" ] & [ -f "$cartfile" ]; then
+      setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "carthage"
+      setCarthageDependency "$projectFolder" "$projectName" "$platform" "$cartfile"
+  elif [ "$branch" != "" ]; then
+      setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "cocoapods"
+      setBowBranchDependency "$projectFolder" "$projectName" "$platform" "$branch"
+  else # version
+      setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "cocoapods"
+      setBowVersionDependency "$projectFolder" "$projectName" "$platform" "$version"
   fi
 }
 
+setCocoaPodsDependency() {
+    local projectFolder="$1" # parameter `projectFolder`
+    local projectName="$2"   # parameter `projectName`
+    local platform="$3"      # parameter `platform`
+    local podfile="$4"       # parameter `podfile`
+    local podfilePath="$projectFolder/Podfile"
+
+    echo -ne "${normal}Updating${green} podfile ($podfileName)${reset}..."
+
+    if [ -f "$podfilePath" ]; then
+        podfileName=`echo "$podfile" | rev | cut -d'/' -f -1 | rev`
+
+        rm -rf "$podfilePath" 1>/dev/null 2>/dev/null
+        cp "$podfile" "$podfilePath" 1>/dev/null 2>/dev/null
+
+        target=`cat "$podfilePath" | grep "target"`
+        sed -i '' s/"$target"/"target '$projectName' do"/g "$podfilePath"
+
+        echo " ✅"
+    else
+        echo " ❌"
+        echo "[!] ${bold}${red}error: ${reset}can not find podfile '$podfilePath'"
+        exit 1
+    fi
+}
+
+setBowBranchDependency() {
+    local projectFolder="$1" # parameter `projectFolder`
+    local projectName="$2"   # parameter `projectName`
+    local platform="$3"      # parameter `platform`
+    local branch="$4"        # parameter `branch`
+    local podfilePath="$projectFolder/Podfile"
+
+    echo -ne "${normal}Updating${green} branch ($branch)${reset}..."
+
+    if [ -f "$podfilePath" ]; then
+        branch=$(echo "$branch" | sed 's/\//\\\//g')
+        sed -i '' s/"\"~> 0.0.0\""/":git => 'https\:\/\/github.com\/bow-swift\/bow.git', :branch => '$branch'"/g "$podfilePath"
+        echo " ✅"
+    else
+        echo " ❌"
+        echo "[!] ${bold}${red}error: ${reset}can not find file '$podfilePath' to set the Bow's branch to '$branch'"
+        exit 1
+    fi
+}
+
+setBowVersionDependency() {
+    local projectFolder="$1" # parameter `projectFolder`
+    local projectName="$2"   # parameter `projectName`
+    local platform="$3"      # parameter `platform`
+    local version="$4"       # parameter `version`
+    local podfilePath="$projectFolder/Podfile"
+
+    echo -ne "${normal}Updating${green} version ($branch)${reset}..."
+
+    if [ -f "$podfilePath" ]; then
+        sed -i '' s/"~> 0.0.0"/"~> $version"/g "$podfilePath"
+        echo " ✅"
+    else
+        echo " ❌"
+        echo "[!] ${bold}${red}error: ${reset}can not find file '$podfilePath' to set the Bow's version to '$version'"
+        exit 1
+    fi
+}
+
 ##
-#   setPlaygroundPlatform(String projectFolder, String projectName, String podfilePath)
+#   setPlaygroundPlatform(String projectFolder, String projectName, String platform, String dependencyManager) throws
 #   - Parameter `projectFolder`: path to the project folder.
 #   - Parameter `projectName`: the project name.
-#   - Parameter `podfile`
+#   - Parameter `platform`: set this platform to playground.
+#   - Parameter `dependencyManager`: set the dependency manager.
 ##
 setPlaygroundPlatform() {
   local projectFolder="$1" # parameter `projectFolder`
   local projectName="$2"   # parameter `projectName`
-  local podfile="$3"       # parameter `podfile`
-  local podfilePath=""
+  local platform="$3"      # parameter `platform`
+  local dependency="$4"    # parameter `dependencyManager`
 
-  if [ "$podfile" != "" ] & [ -f "$podfile" ]; then
-    podfilePath="$podfile"
-  else
-    podfilePath="$projectFolder/Podfile"
-  fi
+  # if [ "$podfile" != "" ] & [ -f "$podfile" ]; then
+  #  podfilePath="$podfile"
+  #else
+  #  podfilePath="$projectFolder/Podfile"
+  #fi
 
-  echo -ne "${normal}Set ${green}$projectName target${reset} to"
+  echo -ne "${normal}Set ${green}$projectName target${reset} to "
 
-  platform=`cat "$podfilePath" | grep -m 1 "platform" | cut -d':' -f 2 | cut -d',' -f 1`
-
-  if [ "ios" = $platform ]; then
+  if [ "ios" = $platform ] || [ "osx" = $platform ]; then
+    mv "$projectFolder/$platform"/* "$projectFolder"
     rm -rf "$projectFolder/osx"
-    mv "$projectFolder"/ios/* "$projectFolder"
     rm -rf "$projectFolder/ios"
-    echo " ${green}iOS${reset} ✅"
 
-  elif [ "osx" = $platform ]; then
-    rm -rf "$projectFolder/ios" 1>/dev/null 2>/dev/null
-    mv "$projectFolder"/osx/* "$projectFolder"
-    rm -rf "$projectFolder/osx" 1>/dev/null 2>/dev/null
-    echo " ${green}macOS${reset} ✅"
-
+    [ "ios" = $platform ] && echo "${green}iOS${reset} ✅" || echo "${green}macOS${reset} ✅"
   else
     echo " ❌"
-    echo "[!] ${bold}${red}error: ${reset}please define a platform (ios | osx) in podfile '$podfilePath'"
+    echo "[!] ${bold}${red}error: ${reset}--platform invalid value '$platform'; you must set platform to 'ios' or 'osx'."
     exit 1
   fi
 }
@@ -234,17 +275,21 @@ set -e
 root=`pwd`
 projectName="$DEFAULT_PLAYGROUND"
 version=$(lastestBowVersion)
+platform="ios"
 branch=""
 podfile=""
+cartfile=""
 
 while [ "$1" != "" ]; do
     case $1 in
         --bow-version | version )    shift; version=$1 ;;
         --bow-branch | branch )      shift; branch=$1 ;;
-        --podfile | podfile )        shift; podfile=$1 ;;
+        --podfile  | podfile )       shift; podfile=$1 ;;
+        --cartfile | cartfile )      shift; cartfile=$1 ;;
 
         --name | name )              shift; projectName=$1 ;;
         --playground | playground )  shift; projectName=$1 ;;
+        --platform | platform )      shift; platform=$1 ;;
 
         -h | --help )                printHelp $@; exit 1 ;;
         * )                          printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}"; exit 1
@@ -255,4 +300,4 @@ done
 projectFolder="$root/$projectName"
 
 playground "$root" "$projectName"
-setDependency "$projectFolder" "$projectName" "$version" "$branch" "$podfile"
+setDependency "$projectFolder" "$projectName" "$platform" "$version" "$branch" "$cartfile" "$podfile"
