Improve error information in nef-playground
More specific in error when you can not build playground because another project with the same name already exist.

diff --git a/bin/nef-playground b/bin/nef-playground
--- a/bin/nef-playground
+++ b/bin/nef-playground
@@ -99,9 +99,7 @@ checkCocoaPods() {
   if [ "$minorPodVersionRequired" != "$required" ]; then
     echo "[!] ${bold}${red}error: ${reset}required cocoapods version ${bold}'$required'${normal} [found: ${red}'$podVersion'${reset}]"
     echo ""
-    echo "Please ${bold}update your cocoapods${reset}. Options:"
-    echo "      1. sudo gem install cocoapods"
-    echo "      2. brew upgrade cocoapods (using homebrew)"
+    echo "Please ${bold}update your cocoapods${reset}. Run: 'sudo gem install cocoapods'"
     echo ""
     exit 1
   fi
@@ -124,6 +122,12 @@ playground() {
   cd $root
   echo -ne "${normal}Installing ${green}Playground ($projectName)${reset}..."
 
+  if [ -d "$projectName" ]; then
+    echo " ❌"
+    echo "[!] ${bold}${red}error: ${reset}destination path '$projectName' already exists and is not an empty directory."
+    exit 1
+  fi
+
   pod lib create "$projectName" --template-url="$NEF_TEMPLATE" 1> "$tempLog" 2>&1
   makeStructure "$projectFolder"
   mv "$tempLog" "$log"
@@ -135,7 +139,7 @@ playground() {
 
   if [ "${#error}" -gt 0 ] || [ "${#fatalError}" -gt 0 ] || [ "${#gemError}" -gt 0 ] || [ "${#otherErrors}" -gt 0 ]; then
     echo " ❌"
-    echo "[!] ${bold}${red}error: ${reset}${bold}building plaground ($projectName)${normal} review '$log' for more information."
+    echo "[!] ${bold}${red}error: ${reset}review '$log' for more information."
     exit 1
   else
     echo " ✅"
