added checking to in args

diff --git a/bin/nef-playground b/bin/nef-playground
--- a/bin/nef-playground
+++ b/bin/nef-playground
@@ -10,7 +10,26 @@ normal=$(tput sgr0)
 
 red=$(tput setaf 1)
 green=$(tput setaf 2)
+lime=$(tput setaf 190)
 reset=$(tput sgr0)
+
+#: IN - Help
+
+##
+#   printHelp()
+##
+printHelp() {
+    latestVersion=$(lastestBowVersion)
+
+    echo ""
+    echo "${normal}$0 ${bold}--name ${normal}<project> ${bold}--version ${normal}<number format: 0.0.0>"
+    echo ""
+    echo "    ${lime}${bold}name${reset}${normal} create a playground project using this name [default: $DEFAULT_PLAYGROUND]"
+    echo "    ${lime}${bold}version${reset}${normal} bow's version to use [default: $latestVersion]"
+    echo ""
+}
+
+#: - Playground
 
 ##
 #   setBowVersion(String projectFolder, String version)
@@ -63,7 +82,7 @@ playground() {
 
   if [ "${#error}" -gt 0 ] || [ "${#fatalError}" -gt 0 ]; then
     echo " ❌"
-    echo "${bold}${red}error: ${reset}${bold}building plaground${normal} review '$log' for more information."
+    echo "[!] ${bold}${red}error: ${reset}${bold}building plaground${normal} review '$log' for more information."
     exit 1
   else
     echo " ✅"
@@ -90,13 +109,26 @@ cleanStructure() {
 }
 
 
-#: MAIN
+#: - MAIN
 set -e
 
 root=`pwd`
 projectName=$DEFAULT_PLAYGROUND
+version=$(lastestBowVersion)
+
+while [ "$1" != "" ]; do
+    case $1 in
+        -v | --version | version )        shift; version=$1 ;;
+        -n | --name | name )              shift; projectName=$1 ;;
+        -p | --playground | playground )  shift; projectName=$1 ;;
+        -h | --help )                     printHelp $@; exit 1 ;;
+        * )                               printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}"; exit 1
+    esac
+    shift
+done
+
 projectFolder="$root/$projectName"
 
 playground "$root" "$projectName"
-setBowVersion "$projectFolder" $(lastestBowVersion)
+setBowVersion "$projectFolder" "$version"
 nefc install  "$projectFolder"
