updated nef playground to use carthage dependency (and cocoa pods)

diff --git a/bin/nef-playground b/bin/nef-playground
--- a/bin/nef-playground
+++ b/bin/nef-playground
@@ -57,18 +57,40 @@ setDependency() {
   local podfile="$7"       # parameter `podfile`
 
   if [ "$podfile" != "" ] & [ -f "$podfile" ]; then
+      checkCocoaPods
       setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "cocoapods"
       setCocoaPodsDependency "$projectFolder" "$projectName" "$platform" "$podfile"
   elif [ "$cartfile" != "" ] & [ -f "$cartfile" ]; then
       setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "carthage"
       setCarthageDependency "$projectFolder" "$projectName" "$platform" "$cartfile"
   elif [ "$branch" != "" ]; then
+      checkCocoaPods
       setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "cocoapods"
       setBowBranchDependency "$projectFolder" "$projectName" "$platform" "$branch"
   else # version
+      checkCocoaPods
       setPlaygroundPlatform "$projectFolder" "$projectName" "$platform" "cocoapods"
       setBowVersionDependency "$projectFolder" "$projectName" "$platform" "$version"
   fi
+}
+
+setCarthageDependency() {
+    local projectFolder="$1" # parameter `projectFolder`
+    local projectName="$2"   # parameter `projectName`
+    local platform="$3"      # parameter `platform`
+    local cartfile="$4"      # parameter `cartfile`
+
+    podfilePath="$projectFolder/Podfile"
+    cartfilePath="$projectFolder/Cartfile"
+    cartfileName=`echo "$cartfile" | rev | cut -d'/' -f -1 | rev`
+
+    echo -ne "${normal}Updating${green} carfile ($cartfileName)${reset}..."
+
+    rm -rf "$podfilePath" 1>/dev/null 2>/dev/null
+    rm -rf "$cartfilePath" 1>/dev/null 2>/dev/null
+    cp "$cartfile" "$cartfilePath" 1>/dev/null 2>/dev/null
+
+    echo " ✅"
 }
 
 setCocoaPodsDependency() {
@@ -76,25 +98,19 @@ setCocoaPodsDependency() {
     local projectName="$2"   # parameter `projectName`
     local platform="$3"      # parameter `platform`
     local podfile="$4"       # parameter `podfile`
-    local podfilePath="$projectFolder/Podfile"
+
+    podfilePath="$projectFolder/Podfile"
+    podfileName=`echo "$podfile" | rev | cut -d'/' -f -1 | rev`
 
     echo -ne "${normal}Updating${green} podfile ($podfileName)${reset}..."
 
-    if [ -f "$podfilePath" ]; then
-        podfileName=`echo "$podfile" | rev | cut -d'/' -f -1 | rev`
+    rm -rf "$podfilePath" 1>/dev/null 2>/dev/null
+    cp "$podfile" "$podfilePath" 1>/dev/null 2>/dev/null
 
-        rm -rf "$podfilePath" 1>/dev/null 2>/dev/null
-        cp "$podfile" "$podfilePath" 1>/dev/null 2>/dev/null
+    target=`cat "$podfilePath" | grep "target"`
+    sed -i '' s/"$target"/"target '$projectName' do"/g "$podfilePath"
 
-        target=`cat "$podfilePath" | grep "target"`
-        sed -i '' s/"$target"/"target '$projectName' do"/g "$podfilePath"
-
-        echo " ✅"
-    else
-        echo " ❌"
-        echo "[!] ${bold}${red}error: ${reset}can not find podfile '$podfilePath'"
-        exit 1
-    fi
+    echo " ✅"
 }
 
 setBowBranchDependency() {
@@ -124,7 +140,7 @@ setBowVersionDependency() {
     local version="$4"       # parameter `version`
     local podfilePath="$projectFolder/Podfile"
 
-    echo -ne "${normal}Updating${green} version ($branch)${reset}..."
+    echo -ne "${normal}Updating${green} version ($version)${reset}..."
 
     if [ -f "$podfilePath" ]; then
         sed -i '' s/"~> 0.0.0"/"~> $version"/g "$podfilePath"
@@ -134,6 +150,29 @@ setBowVersionDependency() {
         echo "[!] ${bold}${red}error: ${reset}can not find file '$podfilePath' to set the Bow's version to '$version'"
         exit 1
     fi
+}
+
+##
+#   checkCocoaPods() throws
+##
+checkCocoaPods() {
+  totalCommandsPod=$(command -v pod | wc -l)
+  if [ $totalCommandsPod -eq 0 ]; then
+    echo "[!] ${bold}${red}error: ${reset}required cocoapods. Please ${bold}install cocoapods${reset}. Run: 'sudo gem install cocoapods'"
+    exit 1
+  fi
+
+  requiredVersion='1.6.1'
+  podVersion=`pod --version`
+  minorPodVersionRequired=(`printf "$podVersion\n$requiredVersion\n" | sort`)
+
+  if [ "$minorPodVersionRequired" != "$requiredVersion" ]; then
+    echo "[!] ${bold}${red}error: ${reset}required cocoapods version ${bold}'$requiredVersion'${normal} [found: ${red}'$podVersion'${reset}]"
+    echo ""
+    echo "Please ${bold}update your cocoapods${reset}. Run: 'sudo gem install cocoapods'"
+    echo ""
+    exit 1
+  fi
 }
 
 ##
@@ -149,18 +188,14 @@ setPlaygroundPlatform() {
   local platform="$3"      # parameter `platform`
   local dependency="$4"    # parameter `dependencyManager`
 
-  # if [ "$podfile" != "" ] & [ -f "$podfile" ]; then
-  #  podfilePath="$podfile"
-  #else
-  #  podfilePath="$projectFolder/Podfile"
-  #fi
-
   echo -ne "${normal}Set ${green}$projectName target${reset} to "
 
   if [ "ios" = $platform ] || [ "osx" = $platform ]; then
-    mv "$projectFolder/$platform"/* "$projectFolder"
+    mv "$projectFolder/$platform/$dependency"/* "$projectFolder"
     rm -rf "$projectFolder/osx"
     rm -rf "$projectFolder/ios"
+    rm -rf "$projectFolder/cocoapods"
+    rm -rf "$projectFolder/carthage"
 
     [ "ios" = $platform ] && echo "${green}iOS${reset} ✅" || echo "${green}macOS${reset} ✅"
   else
