added checking for cocoapods version

diff --git a/bin/nef-playground b/bin/nef-playground
--- a/bin/nef-playground
+++ b/bin/nef-playground
@@ -89,6 +89,25 @@ lastestBowVersion() {
 }
 
 ##
+#   checkCocoaPods() throws
+##
+checkCocoaPods() {
+  required='1.6.1'
+  podVersion=`pod --version`
+  minorPodVersionRequired=(`printf "$podVersion\n$required\n" | sort`)
+
+  if [ "$minorPodVersionRequired" != "$required" ]; then
+    echo "[!] ${bold}${red}error: ${reset}required cocoapods version ${bold}'$required'${normal} [found: ${red}'$podVersion'${reset}]"
+    echo ""
+    echo "Please ${bold}update your cocoapods${reset}. Options:"
+    echo "      1. sudo gem install cocoapods"
+    echo "      2. brew upgrade cocoapods (using homebrew)"
+    echo ""
+    exit 1
+  fi
+}
+
+##
 #   playground(String parent, String projecName)
 #   - Parameter `parent`: path to the project parent.
 #   - Parameter `projecName`: playground name.
@@ -175,5 +194,6 @@ done
 
 projectFolder="$root/$projectName"
 
+checkCocoaPods
 playground "$root" "$projectName"
 setBowVersion "$projectFolder" "$version" "$branch" "$podfile"
