fix markdown script to render markdown playgrounds using page filename

diff --git a/bin/nef-markdown b/bin/nef-markdown
--- a/bin/nef-markdown
+++ b/bin/nef-markdown
@@ -28,44 +28,44 @@ printHelp() {
 #: - Render
 
 ##
-#   generateDocumentation(String project, String output)
+#   generateDocumentation(String projectPath, String outputPath)
 #   - Parameter `project`: path to the project folder.
-#   - Parameter `output`: path where to render the Markdown.
+#   - Parameter `outputPath`: path where to render the Markdown.
 ##
 generateMarkdown() {
-    local projectPath="$1" # parameter 'project'
-    local outputPath="$2"  # parameter 'output'
+    local projectPath="$1" # parameter 'projectPath'
+    local outputPath="$2"  # parameter 'outputPath'
 
     makeStructure "$projectPath" "$outputPath"
     buildMarkdown "$projectPath" "$outputPath"
 }
 
 ##
-#   buildMarkdown(String project, String output)
-#   - Parameter `project`: path to the project folder.
-#   - Parameter `output`: path where to render the Markdown.
+#   buildMarkdown(String projectPath, String outputPath)
+#   - Parameter `projectPath`: path to the project folder.
+#   - Parameter `outputPath`: path where to render the Markdown.
 ##
 buildMarkdown() {
-    local projectPath="$1"
-    local outputPath="$2"
+    local projectPath="$1" # parameter 'projectPath'
+    local outputPath="$2"  # parameter 'outputPath'
 
     playgrounds "$projectPath"
 
     for playground in "${playgrounds[@]}"; do
         playgroundName=`echo "$playground" | rev | cut -d'/' -f -1 | cut -d'.' -f 2- | rev`
         playgroundPath="$projectPath/$playground"
+        output="$outputPath/$playgroundName"
 
         echo -ne "${normal}Rendering Markdown files from ${green}Playground ($playgroundName)${reset}..."
 
+        cleanStructure "$output"
+        mkdir -p "$output"
         pagesInPlayground "$playgroundPath"
 
         for pagePath in "${pagesInPlayground[@]}"; do
             pageName=`echo "$pagePath" | rev | cut -d'/' -f -1 | cut -d'.' -f 2- | rev`
-            output="$outputPath/$playgroundName"
             log="$projectPath/$LOG_PATH/$playgroundName-$pageName.log"
 
-            cleanStructure "$output"
-            mkdir -p "$output"
             nef-markdown-page --from "$pagePath" --to "$output" --filename "$pageName" 1> "$log" 2>&1
 
             installed=`grep "RENDER SUCCEEDED" "$log"`
@@ -81,25 +81,25 @@ buildMarkdown() {
 }
 
 ##
-#   makeStructure(String project, String output)
+#   makeStructure(String project, String outputPath)
 #   - Parameter `project`: path to the project folder.
-#   - Parameter `output`: path where render the markdown.
+#   - Parameter `outputPath`: path where render the markdown.
 ##
 makeStructure() {
-  set +e
-  local logPath="$1/$LOG_PATH"  # parameter `project`
-  local outputPath="$2"         # parameter `output`
+    set +e
+    local logPath="$1/$LOG_PATH"  # parameter `project`
+    local outputPath="$2"         # parameter `outputPath`
 
-  cleanStructure "$output/*.md"
-  mkdir -p "$logPath"
-  mkdir -p "$outputPath"
+    cleanStructure "$outputPath/*/*.md"
+    mkdir -p "$logPath"
+    mkdir -p "$outputPath"
 }
 
 #: - MAIN
 set -e
 
 # Load common nef library
-commonNefLibName="nef-common"
+commonNefLibName="/Users/miguelangel/Documents/3.projects/47deg/nef/bin/nef-common"
 commonNefLibPath=$(which "$commonNefLibName")
 source "$commonNefLibPath"
 
@@ -110,10 +110,10 @@ outputPath=""
 
 while [ "$1" != "" ]; do
     case $1 in
-        --project | project )     shift; projectPath=$1 ;;
-        --output  | output )      shift; outputPath=$1 ;;
-        --help )                  printHelp $@; exit 1 ;;
-        * )                       printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}"; exit 1
+        --project | project )  shift; projectPath=$1 ;;
+        --output  | output )   shift; outputPath=$1 ;;
+        --help )               printHelp $@; exit 1 ;;
+        * )                    printHelp $@; echo "${bold}[!] ${normal}${red}error:${reset} invalid argument: ${red}$1${reset}"; exit 1
     esac
     shift
 done
